services:
  cpp_app:
    platform: linux/arm64
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "80:8080"
    logging:
      driver: awslogs
      options:
        awslogs-group: my-project
        awslogs-region: us-east-1
        awslogs-stream-prefix: cpp-app 